---
parameters:
- name: pool
  type: string
  displayName: 'AKS Pool Name'
- name: tf_azure_service_connection
  type: string
  displayName: 'Azure Service Connection Name'
- name: tf_arm_environment
  type: string
  displayName: 'ARM Environment'
- name: tf_arm_subscription_id
  type: string
  displayName: 'ARM Subscription ID'
- name: workdir
  type: string
  default: '.'
  displayName: 'Working Directory'
- name: tf_plan_command_options
  type: string
  default: ''
  displayName: 'Terraform Plan Command Options'

stages:
- stage: TerragruntPlan
  jobs:
  - deployment: Terragrunt_Plan
    pool: $(pool)
    environment: terragrunt_plan
    continueOnError: 'false'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: 'Terragrunt Plan'
            inputs:
              scriptType: bash
              scriptLocation: inlineScript
              azureSubscription: $(tf_azure_service_connection)
              addSpnToEnvironment: true
              inlineScript: |
                export ARM_ENVIRONMENT=$(tf_arm_environment)
                export ARM_CLIENT_ID=$servicePrincipalId
                export ARM_CLIENT_SECRET=$servicePrincipalKey
                export ARM_SUBSCRIPTION_ID=$(tf_arm_subscription_id)
                export ARM_TENANT_ID=$tenantId
                which terraform
                which terragrunt
                terragrunt plan-all $(tf_plan_command_options)
