---
parameters:
- name: pool
  type: string
  displayName: 'AKS Pool Name'
- name: azure_service_connection
  type: string
  displayName: 'Azure Service Connection Name'
- name: arm_environment
  type: string
  displayName: 'ARM Environment'
- name: arm_subscription_id
  type: string
  displayName: 'ARM Subscription ID'
- name: workdir
  type: string
  default: '.'
  displayName: 'Working Directory'
- name: tf_plan_command_options
  type: string
  default: ''
  displayName: 'Terraform Plan Command Options'

jobs:
- job: Terragrunt_Plan
  pool: $(pool)
  environment: terragrunt_plan
  continueOnError: 'false'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzureCLI@2
          displayName: 'Terragrunt Plan'
          inputs:
            scriptType: bash
            scriptLocation: inlineScript
            azureSubscription: $(azure_service_connection)
            addSpnToEnvironment: true
            inlineScript: |
              export ARM_ENVIRONMENT=$(arm_environment)
              export ARM_CLIENT_ID=$servicePrincipalId
              export ARM_CLIENT_SECRET=$servicePrincipalKey
              export ARM_SUBSCRIPTION_ID=$(arm_subscription_id)
              export ARM_TENANT_ID=$tenantId
              directory=$(workdir)
              cd ${directory}
              terragrunt plan $(tf_plan_command_options)
