---
parameters:
- name: pool
  type: string
  displayName: 'AKS Pool Name'
- name: tf_azure_service_connection
  type: string
  displayName: 'Azure Service Connection Name'
- name: tf_arm_environment
  type: string
  displayName: 'ARM Environment'
- name: tf_arm_subscription_id
  type: string
  displayName: 'ARM Subscription ID'
- name: workdir
  type: string
  default: '.'
  displayName: 'Working Directory'
- name: tf_validate_command_options
  type: string
  default: ''
  displayName: 'Terraform Validate Command Options'

stages:
- stage: Terragrunt_Preflight_Check
  jobs:
  - deployment: Terragrunt_Preflight_Check
    displayName: Terragrunt_Preflight_Check
    pool: $(pool)
    environment: terragrunt_preflight
    continueOnError: 'false'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: main.yaml

          - task: AzureCLI@2
            displayName: 'Terragrunt Validate'
            inputs:
              scriptType: bash
              scriptLocation: inlineScript
              azureSubscription: $(tf_azure_service_connection)
              addSpnToEnvironment: true
              inlineScript: |
                export ARM_ENVIRONMENT=$(tf_arm_environment)
                export ARM_CLIENT_ID=$servicePrincipalId
                export ARM_CLIENT_SECRET=$servicePrincipalKey
                export ARM_SUBSCRIPTION_ID=$(atf_rm_subscription_id)
                export ARM_TENANT_ID=$tenantId
                directory=$(workdir)
                cd ${directory}
                terragrunt validate $(tf_validate_command_options)
